### PR TITLE
Ignore errors / warnings when using deprecated cl1.2 functions

### PR DESCRIPTION
**Pull request by pavanky**
This change is [Reviewable](https://reviewable.io/reviews/clmathlibraries/clsparse/189)

### CODE REVIEW

**Comment by pavanky** [comment]
This patch reduces the number of warnings in the downloaded version of `cl2.hpp`, so it is not essential in those cases, but it is necessary to build clSparse on the `cl2.hpp` version shipped by various distros containing an older buggy version.

**Comment by kknox** [comment]
Hi @pavanky,
I have existing code in our [FindOpenCL.cmake](https://github.com/clMathLibraries/clSPARSE/blob/develop/src/cmake/FindOpenCL.cmake#L146) that deals with issues like these warnings.  Looks like I had nothing for 1.2.  I would prefer that this fix make it into this file instead.  I'm going to close this PR, and we'll get this patched on monday

**Comment by kknox** [comment]
@pavanky 
I pushed a simple commit with the macro in [FindOpenCL in kknox/develop](https://github.com/kknox/clSPARSE/commit/39fe0ff1991d2324cb3fedf4c654d748b91329a1).  Is there a way to test that this solves the problem?

**Comment by pavanky** [comment]
@kknox that works.

**Comment by pavanky** [comment]
I tested this on an archlinux machine with the packaged version of opencl-headers. You should be able to test the same on either Ubuntu 16.04 or Debian Testing.

**Pull request closed without merging**
